language: python
python:
- 2.7
install:
- pip install -r requirements.txt
- pip install .
- pip install coveralls
script:
- coverage run --source pyIOSXR.iosxr test/test.py -v
after_success: coveralls
deploy:
  provider: pypi
  user: fooelisa
  password:
    secure: EA+bz/sRqivLZsZXxKg2Wb1PxhgiXEbFAiDaw2yCfW/3q+nYlG2R1xPtqI6QNP0/5kuFAEef8dvx1yuCo34zcdNpD71Wg+jVbz8Xq2cS/Tsv0GwnH2KxwVM0VkfvXOh2eDquQt4nGP8yXa6AMAh6E3gOmdYUMyA7ZzeCPLDPii4ICGcCop32MU1I3w2X+vajlQWv3s0c/N3BuCP1Ol811bYPkiLlgAU9LDrZtz/nnoIHurPXuTlj3Gz6VzMjxBK5qiNcz+69cNmVAiQlnahJRHcCZae/NWg/wWIsMqdA0mS1njn8E7XTd4RqgAdWZbcuK/iVTfpVBp/FfFFwIXkbcxiNnjd/J3wzVDcVbDJHAPLcFgYnxyrpVogwIjW01HzjoVjzUHGSOtP1rBF4IKlZwzRvwQdc/Qk+TgZ2Z5fEtsk+1icLwxIN0x9YZhSemrvdDsnItdj9wVoxByaSX3iMpNDsbfBvV7gAvMkAqe1WO0lbIK4htZKJ5ueoWDLKJNKsfMVy0i7N6EEw5emY0JrBdB1k2OCJdih9cnU+fe3YDFq4Zm+/zwjkTy6kX4BrWwHr/RgqSWY11f0TrWoWfI5GzxTL67Qkq/6fjeg+Nf81ts+PUP5+rq71Xi60zxFJ2pMvNxPrFSc+5F2TQG/1x8hPUKGUayaA+YlZMRkM81QauNw=
  on:
    tags: true
    branch: master
